### ISSUE TITLE
Show user posts and replies positions on the scrollbar

### ISSUE THREAD

**Issue by N3-M3-S1S** [TrixiEther/DashchanFork#59] opened 2023-04-15 21:31 UTC
We can show user posts and replies (and may be some other types of posts e.g. doubles/triples/etc, posts with many replies) on the scrollbar (like in some code editors) for more convenient navigation in a thread.

**Comment by TrixiEther** [comment] 2023-04-16 07:59
Duplicate of #52
Ok, I'll reassign the old task, when it's ready - we'll close two things at once

**Comment by TrixiEther** [comment] 2023-04-16 08:01
@N3-M3-S1S or it's another feature, only with scrollbar?

**Comment by N3-M3-S1S** [comment] 2023-04-16 08:47
@TrixiEther this is for the scrollbar only.

**Closed as completed** 2023-05-12 10:40 UTC
Labels: enhancement
